# Generated by Django 4.0.4 on 2022-05-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('edad', models.SmallIntegerField()),
                ('sexo', models.CharField(choices=[(1, 'M'), (2, 'F'), (3, 'NB')], max_length=3)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(1, 'Enviada'), (2, 'Recibida'), (3, 'Aceptada'), (4, 'Cancelada')], max_length=25)),
                ('detalle_fecha', models.DateTimeField()),
                ('detalle_duracion', models.CharField(max_length=25)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Aceptado'), (2, 'En progeso'), (3, 'Completado'), (4, 'Cancelado')], max_length=15)),
                ('monto', models.FloatField()),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_trabajador', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.categoria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.trabajador'),
        ),
        migrations.CreateModel(
            name='MetodoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(1, 'Cobro'), (2, 'Pago')], max_length=10)),
                ('forma', models.CharField(choices=[(1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Paypal'), (4, 'MercadoPago')], max_length=50)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftWorkers.perfil'),
        ),
    ]
