# Generated by Django 4.0.4 on 2022-05-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftWorkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodotransaccion',
            name='forma',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Paypal'), (4, 'MercadoPago')], max_length=50),
        ),
        migrations.AlterField(
            model_name='metodotransaccion',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cobro'), (2, 'Pago')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'M'), (2, 'F'), (3, 'NB')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enviada'), (2, 'Recibida'), (3, 'Aceptada'), (4, 'Cancelada')], max_length=25),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aceptado'), (2, 'En progeso'), (3, 'Completado'), (4, 'Cancelado')], max_length=15),
        ),
    ]
